### PR TITLE
Fix issues when parsing paths from function names and scripts

### LINKED ISSUE #14: Expected argument to be an absolute path or URI: '<unknown>'
```
[ERR!: 10:37:57.169] line 19975: Expected argument to be an absolute path or URI: '<unknown>'
TypeError: Expected argument to be an absolute path or URI: '<unknown>'
    at t.pathOrUriStringToUri (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:5:155602)
    at t.LogProcessor.processScriptSource (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:2:182129)
    at u.dispatchLogRow_ (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:165:35835)
    at u.processLogLine_ (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:165:36292)
    at u.processLogLine (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:165:34581)
    at t.LogProcessor.processContent (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:2:174391)
    at t.measureAsync (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:5:27865)
    at t.LogProcessor.process (/Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:2:174665)
    at /Users/conartist6/.vscode/extensions/rbuckton.deoptexplorer-vscode-1.0.2-darwin-arm64/dist/extension.js:5:42522
```

Line 19975 is: `script-source,168,<unknown>,'__esModule'`

### PR DESCRIPTION
**Pull request by rbuckton**
Function name parsing is currently very squishy because V8's output can be ambiguous. This fixes a few cases to improve parsing and to allow relative paths in some cases.

This also fixes an error in map details parsing I found while investigating this issue.

Fixes #14

### CODE REVIEW

**Comment by rbuckton** [comment]
Pinging a few folks for review. I know you may not have context on the changes, but I'd appreciate a 2nd pair of eyes.

File: src/extension/components/logProcessor.ts [hunk 1]
```diff
@@ -73,7 +74,7 @@ const unusedPropertyFieldsRegExp = /\n - unused property fields: (\d+)\r?\n/;
 // const mapDetailsFieldKeyRegExp = /^ - (?<key>deprecated_map|stable_map|migration_target|dictionary_map|named_interceptor|indexed_interceptor|may_have_interesting_symbols|undetectable|callable|constructor|has_prototype_slot(?: \(non-instance prototype\))?|access_check_needed|non-extensible|prototype_map)$/;
 // const mapDetailsInstanceDescriptorsFieldRegExp = /^ - (?<key>instance descriptors) (?<own>\(own\) )?#(?<count>): (?<value>.*)$/;
 const mapDetailsPropertyLikeRegExp = /^  \[\d+\]:/;
-const mapDetailsPropertyRegExp = /^  \[\d+\]: 0x[a-fA-F0-9]+ <(?<type>String\[#\d+\]|Symbol): (?<key>[^>]+)> \((?:const )?(?:data|accessor)(?: field(?: \d+)?(?::(?<mnemonic>\w+))?| descriptor)(?:, p: \d+)?(?:, attrs: \[(?<attrs>[W_][E_][C_])\])?\) @ (?:Any|None|Class\((?<classMapAddress>[a-fA-F0-9]+)\))?/;
+const mapDetailsPropertyRegExp =  /^  \[\d+\]: 0x[a-fA-F0-9]+ <(?<type>String\[#?\d+\]|Symbol): (?<key>[^>]*)> \((?:const )?(?:data|accessor)(?: field(?: \d+)?(?::(?<mnemonic>\w+))?| descriptor)(?:, p: \d+)?(?:, attrs: \[(?<attrs>[W_][E_][C_])\])?\) @ (?:Any|None|Class\((?<classMapAddress>[a-fA-F0-9]+)\))?/;
```
Comment (jakebailey) [inline src/extension/components/logProcessor.ts:77]: Seems like there's a spurious formatting change here, fwiw.

**Review by jakebailey — APPROVED** [review]
